### ISSUE TITLE
EFI Usage

### ISSUE THREAD

**Issue by narindraditantyo** [Colin-XKL/Dell-G3-3579-EFI#1]
Can I use this on Mojave 10.14.6?

**Comment by Colin-XKL** [comment]
> Can I use this on Mojave 10.14.6?

Well, I've only tested the EFI file on 10.14.2. Since there're very little differences between 10.14.x, so I think it would work well on 10.14.6, too.

**Comment by Colin-XKL** [comment]
Sometimes there would be about three minutes black screen on cold boot, but don't worry, the system would boot normally with a sound. Next time when you hot-reboot the system, the black screen would disappear.
