### ISSUE TITLE
安装前和安装后 笔记本自带键盘和触摸板都不能用 我用的10.14.5的clover镜像

### ISSUE THREAD

**Issue by beargates** [Colin-XKL/Dell-G3-3579-EFI#2]

**Comment by Colin-XKL** [comment]
是相同机型吗？我这边的自带键盘和触控板都是可以直接驱动的。

**Comment by beargates** [comment]
是相同机型 我换了10.14.2也可以了




| |
15910448385
|
|
邮箱：15910448385@163.com
|

Signature is customized by Netease Mail Master

在2020年04月06日 13:48，Colin-XKL 写道：

是相同机型吗？我这边的自带键盘和触控板都是可以直接驱动的。
